{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "60800e10",
   "metadata": {
    "_cell_guid": "b1076dfc-b9ad-4769-8c92-a6c4dae69d19",
    "_uuid": "8f2839f25d086af736a60e9eeb907d3b93b6e0e5",
    "execution": {
     "iopub.execute_input": "2026-03-24T02:43:49.246133Z",
     "iopub.status.busy": "2026-03-24T02:43:49.245949Z",
     "iopub.status.idle": "2026-03-24T02:47:13.802304Z",
     "shell.execute_reply": "2026-03-24T02:47:13.801848Z"
    },
    "papermill": {
     "duration": 204.560043,
     "end_time": "2026-03-24T02:47:13.803384+00:00",
     "exception": false,
     "start_time": "2026-03-24T02:43:49.243341+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Đang giải nén /kaggle/input/notebooks/saketposwal/aimo-3-vllm-v18/wheels.tar.gz...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_44/2821163466.py:42: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.\n",
      "  tar.extractall(path=EXTRACT_DIR)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Đang xóa wheel để bảo vệ hệ thống: /kaggle/working/vllm_wheels/wheels/protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl\n",
      "Đang xóa wheel để bảo vệ hệ thống: /kaggle/working/vllm_wheels/wheels/pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl\n",
      "Đang patch metadata protobuf để vượt qua dependency check của pip...\n",
      "Đang cài đặt vLLM từ: /kaggle/working/vllm_wheels/wheels\n",
      "Looking in links: /kaggle/working/vllm_wheels/wheels\n",
      "Processing ./vllm_wheels/wheels/vllm-0.18.0-cp38-abi3-manylinux_2_31_x86_64.whl\n",
      "Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm) (2025.11.3)\n",
      "Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (6.2.6)\n",
      "Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from vllm) (5.9.5)\n",
      "Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.1)\n",
      "Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from vllm) (2.0.2)\n",
      "Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.4)\n",
      "Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vllm) (4.67.3)\n",
      "Requirement already satisfied: blake3 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.0.8)\n",
      "Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)\n",
      "Processing ./vllm_wheels/wheels/transformers-4.57.6-py3-none-any.whl (from vllm)\n",
      "Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.2)\n",
      "Requirement already satisfied: protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 in /usr/local/lib/python3.12/dist-packages (from vllm) (5.29.6)\n",
      "Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.133.0)\n",
      "Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.3)\n",
      "Requirement already satisfied: openai<2.25.0,>=1.99.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.23.0)\n",
      "Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.12.3)\n",
      "Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.24.1)\n",
      "Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm) (11.3.0)\n",
      "Processing ./vllm_wheels/wheels/prometheus_fastapi_instrumentator-7.1.0-py3-none-any.whl (from vllm)\n",
      "Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.12.0)\n",
      "Processing ./vllm_wheels/wheels/lm_format_enforcer-0.11.3-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/llguidance-1.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/outlines_core-0.2.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/diskcache-5.6.3-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/lark-1.2.2-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/xgrammar-0.1.32-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (from vllm)\n",
      "Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.15.0)\n",
      "Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.24.3)\n",
      "Processing ./vllm_wheels/wheels/partial_json_parser-0.2.1.1.post7-py3-none-any.whl (from vllm)\n",
      "Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)\n",
      "Processing ./vllm_wheels/wheels/msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/gguf-0.18.0-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/mistral_common-1.10.0-py3-none-any.whl (from mistral_common[image]>=1.10.0->vllm)\n",
      "Requirement already satisfied: opencv-python-headless>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.13.0.92)\n",
      "Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm) (6.0.3)\n",
      "Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)\n",
      "Processing ./vllm_wheels/wheels/setuptools-80.10.2-py3-none-any.whl (from vllm)\n",
      "Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.2)\n",
      "Processing ./vllm_wheels/wheels/compressed_tensors-0.13.0-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/depyf-0.20.0-py3-none-any.whl (from vllm)\n",
      "Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.2)\n",
      "Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm) (1.1.1)\n",
      "Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.0.0)\n",
      "Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from vllm) (1.13.0)\n",
      "Processing ./vllm_wheels/wheels/pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/cbor2-5.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/anthropic-0.86.0-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/model_hosting_container_standards-0.1.14-py3-none-any.whl (from vllm)\n",
      "Requirement already satisfied: mcp in /usr/local/lib/python3.12/dist-packages (from vllm) (1.26.0)\n",
      "Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.38.0)\n",
      "Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.38.0)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_exporter_otlp-1.40.0-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_semantic_conventions_ai-0.5.0-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/numba-0.61.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from vllm)\n",
      "Requirement already satisfied: torch==2.10.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.10.0+cu128)\n",
      "Requirement already satisfied: torchaudio==2.10.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.10.0+cu128)\n",
      "Requirement already satisfied: torchvision==0.25.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.25.0+cu128)\n",
      "Processing ./vllm_wheels/wheels/flashinfer_python-0.6.6-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/nvidia_cudnn_frontend-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/nvidia_cutlass_dsl-4.4.2-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/quack_kernels-0.3.4-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/loguru-0.7.3-py3-none-any.whl (from compressed-tensors==0.13.0->vllm)\n",
      "Processing ./vllm_wheels/wheels/astor-0.8.1-py2.py3-none-any.whl (from depyf==0.20.0->vllm)\n",
      "Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.4.1)\n",
      "Processing ./vllm_wheels/wheels/apache_tvm_ffi-0.1.9-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (from flashinfer-python==0.6.6->vllm)\n",
      "Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.6->vllm) (8.3.1)\n",
      "Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.6->vllm) (13.590.48)\n",
      "Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.6->vllm) (26.0)\n",
      "Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.6->vllm) (0.9.0)\n",
      "Processing ./vllm_wheels/wheels/interegular-0.3.3-py37-none-any.whl (from lm-format-enforcer==0.11.3->vllm)\n",
      "Processing ./vllm_wheels/wheels/llvmlite-0.44.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from numba==0.61.2->vllm)\n",
      "Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (1.14.0)\n",
      "Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (3.6.1)\n",
      "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (3.1.6)\n",
      "Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (2026.2.0)\n",
      "Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (12.9.4)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (12.8.93)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (12.8.90)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (12.8.90)\n",
      "Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (9.10.2.21)\n",
      "Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (12.8.4.1)\n",
      "Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (11.3.3.83)\n",
      "Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (10.3.9.90)\n",
      "Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (11.7.3.90)\n",
      "Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (12.5.8.93)\n",
      "Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (0.7.1)\n",
      "Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (2.27.5)\n",
      "Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (3.4.5)\n",
      "Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (12.8.90)\n",
      "Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (12.8.93)\n",
      "Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (1.13.1.3)\n",
      "Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.10.0->vllm) (3.6.0)\n",
      "Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch==2.10.0->vllm) (1.3.5)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (25.4.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.8.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (6.7.1)\n",
      "Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (0.4.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.22.0)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (4.12.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (1.9.0)\n",
      "Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.17.0)\n",
      "Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.28.1)\n",
      "Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.10.0)\n",
      "Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (1.3.1)\n",
      "Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.52.1)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.4.2)\n",
      "Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.0.4)\n",
      "Processing ./vllm_wheels/wheels/fastapi_cli-0.0.24-py3-none-any.whl (from fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm)\n",
      "Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.0.22)\n",
      "Requirement already satisfied: email-validator>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.3.0)\n",
      "Requirement already satisfied: uvicorn>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (0.41.0)\n",
      "Requirement already satisfied: pydantic-settings>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.13.1)\n",
      "Processing ./vllm_wheels/wheels/pydantic_extra_types-2.11.1-py3-none-any.whl (from fastapi[standard]>=0.115.0->vllm)\n",
      "Requirement already satisfied: jsonschema>=4.21.1 in /usr/local/lib/python3.12/dist-packages (from mistral_common>=1.10.0->mistral_common[image]>=1.10.0->vllm) (4.26.0)\n",
      "Requirement already satisfied: jmespath in /usr/local/lib/python3.12/dist-packages (from model-hosting-container-standards<1.0.0,>=0.1.13->vllm) (1.1.0)\n",
      "Processing ./vllm_wheels/wheels/supervisor-4.3.0-py2.py3-none-any.whl (from model-hosting-container-standards<1.0.0,>=0.1.13->vllm)\n",
      "Processing ./vllm_wheels/wheels/nvidia_cutlass_dsl_libs_base-4.4.2-cp312-cp312-manylinux_2_28_x86_64.whl (from nvidia-cutlass-dsl>=4.4.0.dev1->vllm)\n",
      "Requirement already satisfied: cuda-python>=12.8 in /usr/local/lib/python3.12/dist-packages (from nvidia-cutlass-dsl-libs-base==4.4.2->nvidia-cutlass-dsl>=4.4.0.dev1->vllm) (12.9.4)\n",
      "Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.27.0->vllm) (8.7.1)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl (from opentelemetry-exporter-otlp>=1.27.0->vllm)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_exporter_otlp_proto_http-1.40.0-py3-none-any.whl (from opentelemetry-exporter-otlp>=1.27.0->vllm)\n",
      "Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.27.0->vllm) (1.72.0)\n",
      "Requirement already satisfied: grpcio<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.27.0->vllm) (1.78.1)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl (from opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.27.0->vllm)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_proto-1.40.0-py3-none-any.whl (from opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.27.0->vllm)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_sdk-1.40.0-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_api-1.40.0-py3-none-any.whl (from vllm)\n",
      "Processing ./vllm_wheels/wheels/opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (from opentelemetry-sdk>=1.27.0->vllm)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (2.41.4)\n",
      "Processing ./vllm_wheels/wheels/torch_c_dlpack_ext-0.1.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (from quack-kernels>=0.2.7->vllm)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.11)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2026.1.4)\n",
      "Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.21.1->vllm) (1.4.1)\n",
      "Processing ./vllm_wheels/wheels/huggingface_hub-0.36.2-py3-none-any.whl (from tokenizers>=0.21.1->vllm)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.56.0->vllm) (0.7.0)\n",
      "Requirement already satisfied: httpx-sse>=0.4 in /usr/local/lib/python3.12/dist-packages (from mcp->vllm) (0.4.3)\n",
      "Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->mcp->vllm) (2.11.0)\n",
      "Requirement already satisfied: sse-starlette>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from mcp->vllm) (3.2.0)\n",
      "Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from email-validator>=2.0.0->fastapi[standard]>=0.115.0->vllm) (2.8.0)\n",
      "Requirement already satisfied: typer>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (0.24.1)\n",
      "Processing ./vllm_wheels/wheels/rich_toolkit-0.19.7-py3-none-any.whl (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm)\n",
      "Processing ./vllm_wheels/wheels/fastapi_cloud_cli-0.15.0-py3-none-any.whl (from fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm)\n",
      "Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic>=0.71.0->vllm) (1.0.9)\n",
      "Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic>=0.71.0->vllm) (0.16.0)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.21.1->vllm) (1.3.0)\n",
      "Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.27.0->vllm) (3.23.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.10.0->vllm) (3.0.3)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral_common>=1.10.0->mistral_common[image]>=1.10.0->vllm) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral_common>=1.10.0->mistral_common[image]>=1.10.0->vllm) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral_common>=1.10.0->mistral_common[image]>=1.10.0->vllm) (0.30.0)\n",
      "Processing ./vllm_wheels/wheels/pycountry-26.2.16-py3-none-any.whl (from pydantic-extra-types[pycountry]>=2.10.5->mistral_common>=1.10.0->mistral_common[image]>=1.10.0->vllm)\n",
      "Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0.0->fastapi[standard]>=0.115.0->vllm) (1.2.1)\n",
      "Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->mcp->vllm) (43.0.3)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch==2.10.0->vllm) (1.3.0)\n",
      "Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (0.7.1)\n",
      "Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (0.22.1)\n",
      "Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (15.0.1)\n",
      "Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->mcp->vllm) (2.0.0)\n",
      "Processing ./vllm_wheels/wheels/rignore-0.7.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from fastapi-cloud-cli>=0.1.1->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm)\n",
      "Requirement already satisfied: sentry-sdk>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from fastapi-cloud-cli>=0.1.1->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (2.53.0)\n",
      "Processing ./vllm_wheels/wheels/fastar-0.9.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from fastapi-cloud-cli>=0.1.1->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm)\n",
      "Requirement already satisfied: rich>=13.7.1 in /usr/local/lib/python3.12/dist-packages (from rich-toolkit>=0.14.8->fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (13.9.4)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.16.0->fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (1.5.4)\n",
      "Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->mcp->vllm) (3.0)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.7.1->rich-toolkit>=0.14.8->fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (4.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.7.1->rich-toolkit>=0.14.8->fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (2.19.2)\n",
      "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.7.1->rich-toolkit>=0.14.8->fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == \"standard\"->fastapi[standard]>=0.115.0->vllm) (0.1.2)\n",
      "Installing collected packages: supervisor, setuptools, setproctitle, rignore, pycountry, pybase64, partial-json-parser, outlines_core, opentelemetry-proto, nvidia-cudnn-frontend, msgspec, loguru, llvmlite, llguidance, lark, interegular, ijson, fastar, diskcache, cbor2, astor, apache-tvm-ffi, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, numba, huggingface-hub, gguf, depyf, rich-toolkit, pydantic-extra-types, prometheus-fastapi-instrumentator, opentelemetry-semantic-conventions, openai-harmony, nvidia-cutlass-dsl-libs-base, lm-format-enforcer, anthropic, transformers, torch-c-dlpack-ext, opentelemetry-sdk, nvidia-cutlass-dsl, model-hosting-container-standards, fastapi-cloud-cli, fastapi-cli, xgrammar, quack-kernels, opentelemetry-semantic-conventions-ai, opentelemetry-exporter-otlp-proto-http, opentelemetry-exporter-otlp-proto-grpc, mistral_common, flashinfer-python, compressed-tensors, opentelemetry-exporter-otlp, vllm\n",
      "  Attempting uninstall: setuptools\n",
      "    Found existing installation: setuptools 75.2.0\n",
      "    Uninstalling setuptools-75.2.0:\n",
      "      Successfully uninstalled setuptools-75.2.0\n",
      "  Attempting uninstall: opentelemetry-proto\n",
      "    Found existing installation: opentelemetry-proto 1.38.0\n",
      "    Uninstalling opentelemetry-proto-1.38.0:\n",
      "      Successfully uninstalled opentelemetry-proto-1.38.0\n",
      "  Attempting uninstall: llvmlite\n",
      "    Found existing installation: llvmlite 0.43.0\n",
      "    Uninstalling llvmlite-0.43.0:\n",
      "      Successfully uninstalled llvmlite-0.43.0\n",
      "  Attempting uninstall: lark\n",
      "    Found existing installation: lark 1.3.1\n",
      "    Uninstalling lark-1.3.1:\n",
      "      Successfully uninstalled lark-1.3.1\n",
      "  Attempting uninstall: opentelemetry-exporter-otlp-proto-common\n",
      "    Found existing installation: opentelemetry-exporter-otlp-proto-common 1.38.0\n",
      "    Uninstalling opentelemetry-exporter-otlp-proto-common-1.38.0:\n",
      "      Successfully uninstalled opentelemetry-exporter-otlp-proto-common-1.38.0\n",
      "  Attempting uninstall: opentelemetry-api\n",
      "    Found existing installation: opentelemetry-api 1.38.0\n",
      "    Uninstalling opentelemetry-api-1.38.0:\n",
      "      Successfully uninstalled opentelemetry-api-1.38.0\n",
      "  Attempting uninstall: numba\n",
      "    Found existing installation: numba 0.60.0\n",
      "    Uninstalling numba-0.60.0:\n",
      "      Successfully uninstalled numba-0.60.0\n",
      "  Attempting uninstall: huggingface-hub\n",
      "    Found existing installation: huggingface_hub 1.4.1\n",
      "    Uninstalling huggingface_hub-1.4.1:\n",
      "      Successfully uninstalled huggingface_hub-1.4.1\n",
      "  Attempting uninstall: opentelemetry-semantic-conventions\n",
      "    Found existing installation: opentelemetry-semantic-conventions 0.59b0\n",
      "    Uninstalling opentelemetry-semantic-conventions-0.59b0:\n",
      "      Successfully uninstalled opentelemetry-semantic-conventions-0.59b0\n",
      "  Attempting uninstall: transformers\n",
      "    Found existing installation: transformers 5.0.0\n",
      "    Uninstalling transformers-5.0.0:\n",
      "      Successfully uninstalled transformers-5.0.0\n",
      "  Attempting uninstall: opentelemetry-sdk\n",
      "    Found existing installation: opentelemetry-sdk 1.38.0\n",
      "    Uninstalling opentelemetry-sdk-1.38.0:\n",
      "      Successfully uninstalled opentelemetry-sdk-1.38.0\n",
      "  Attempting uninstall: opentelemetry-exporter-otlp-proto-http\n",
      "    Found existing installation: opentelemetry-exporter-otlp-proto-http 1.38.0\n",
      "    Uninstalling opentelemetry-exporter-otlp-proto-http-1.38.0:\n",
      "      Successfully uninstalled opentelemetry-exporter-otlp-proto-http-1.38.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "google-adk 1.25.1 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.\n",
      "google-adk 1.25.1 requires opentelemetry-api<1.40.0,>=1.36.0, but you have opentelemetry-api 1.40.0 which is incompatible.\n",
      "google-adk 1.25.1 requires opentelemetry-sdk<1.40.0,>=1.36.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.\n",
      "opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Successfully installed anthropic-0.86.0 apache-tvm-ffi-0.1.9 astor-0.8.1 cbor2-5.8.0 compressed-tensors-0.13.0 depyf-0.20.0 diskcache-5.6.3 fastapi-cli-0.0.24 fastapi-cloud-cli-0.15.0 fastar-0.9.0 flashinfer-python-0.6.6 gguf-0.18.0 huggingface-hub-0.36.2 ijson-3.5.0 interegular-0.3.3 lark-1.2.2 llguidance-1.3.0 llvmlite-0.44.0 lm-format-enforcer-0.11.3 loguru-0.7.3 mistral_common-1.10.0 model-hosting-container-standards-0.1.14 msgspec-0.20.0 numba-0.61.2 nvidia-cudnn-frontend-1.18.0 nvidia-cutlass-dsl-4.4.2 nvidia-cutlass-dsl-libs-base-4.4.2 openai-harmony-0.0.8 opentelemetry-api-1.40.0 opentelemetry-exporter-otlp-1.40.0 opentelemetry-exporter-otlp-proto-common-1.40.0 opentelemetry-exporter-otlp-proto-grpc-1.40.0 opentelemetry-exporter-otlp-proto-http-1.40.0 opentelemetry-proto-1.40.0 opentelemetry-sdk-1.40.0 opentelemetry-semantic-conventions-0.61b0 opentelemetry-semantic-conventions-ai-0.5.0 outlines_core-0.2.11 partial-json-parser-0.2.1.1.post7 prometheus-fastapi-instrumentator-7.1.0 pybase64-1.4.3 pycountry-26.2.16 pydantic-extra-types-2.11.1 quack-kernels-0.3.4 rich-toolkit-0.19.7 rignore-0.7.6 setproctitle-1.3.7 setuptools-80.10.2 supervisor-4.3.0 torch-c-dlpack-ext-0.1.5 transformers-4.57.6 vllm-0.18.0 xgrammar-0.1.32\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-24 02:45:28.015160: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1774320328.138033      44 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1774320328.175443      44 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "W0000 00:00:1774320328.480079      44 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1774320328.480097      44 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1774320328.480099      44 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1774320328.480101      44 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initializing LLM Engine...\n",
      "Detected 1 GPUs. Type: NVIDIA H100 80GB HBM3\n",
      "INFO 03-24 02:45:42 [utils.py:233] non-default args: {'max_model_len': 4096, 'gpu_memory_utilization': 0.85, 'disable_log_stats': True, 'quantization': 'AWQ', 'enforce_eager': True, 'model': '/kaggle/input/models/adriansaezmartinez/qwen2.5-math-7b-instruct-awq/transformers/default/1'}\n",
      "INFO 03-24 02:45:57 [model.py:533] Resolved architecture: Qwen2ForCausalLM\n",
      "INFO 03-24 02:45:57 [model.py:1582] Using max model len 4096\n",
      "INFO 03-24 02:45:57 [awq_marlin.py:166] Detected that the model can run with awq_marlin, however you specified quantization=awq explicitly, so forcing awq. Use quantization=awq_marlin for faster inference\n",
      "INFO 03-24 02:45:58 [scheduler.py:231] Chunked prefill is enabled with max_num_batched_tokens=16384.\n",
      "INFO 03-24 02:45:58 [vllm.py:754] Asynchronous scheduling is enabled.\n",
      "WARNING 03-24 02:45:58 [vllm.py:788] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none\n",
      "WARNING 03-24 02:45:58 [vllm.py:799] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.\n",
      "INFO 03-24 02:45:58 [vllm.py:964] Cudagraph is disabled under eager mode\n",
      "INFO 03-24 02:45:58 [compilation.py:289] Enabled custom fusions: norm_quant, act_quant\n",
      "WARNING 03-24 02:45:58 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-24 02:46:04.848341: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1774320364.864100     259 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1774320364.869089     259 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "W0000 00:00:1774320364.881241     259 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1774320364.881263     259 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1774320364.881266     259 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1774320364.881267     259 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(EngineCore pid=259) INFO 03-24 02:46:10 [core.py:103] Initializing a V1 LLM engine (v0.18.0) with config: model='/kaggle/input/models/adriansaezmartinez/qwen2.5-math-7b-instruct-awq/transformers/default/1', speculative_config=None, tokenizer='/kaggle/input/models/adriansaezmartinez/qwen2.5-math-7b-instruct-awq/transformers/default/1', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/kaggle/input/models/adriansaezmartinez/qwen2.5-math-7b-instruct-awq/transformers/default/1, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}\n",
      "(EngineCore pid=259) INFO 03-24 02:46:10 [parallel_state.py:1395] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.19.2.2:51603 backend=nccl\n",
      "(EngineCore pid=259) INFO 03-24 02:46:10 [parallel_state.py:1717] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[W324 02:46:10.391047795 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(EngineCore pid=259) INFO 03-24 02:46:11 [gpu_model_runner.py:4481] Starting to load model /kaggle/input/models/adriansaezmartinez/qwen2.5-math-7b-instruct-awq/transformers/default/1...\n",
      "(EngineCore pid=259) INFO 03-24 02:46:11 [cuda.py:317] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].\n",
      "(EngineCore pid=259) INFO 03-24 02:46:11 [flash_attn.py:598] Using FlashAttention version 3\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]\n",
      "Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:41<00:41, 41.29s/it]\n",
      "Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:51<00:00, 22.96s/it]\n",
      "Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:51<00:00, 25.71s/it]\n",
      "(EngineCore pid=259) \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(EngineCore pid=259) INFO 03-24 02:47:03 [default_loader.py:384] Loading weights took 51.44 seconds\n",
      "(EngineCore pid=259) INFO 03-24 02:47:03 [gpu_model_runner.py:4566] Model loading took 5.2 GiB memory and 51.771950 seconds\n",
      "(EngineCore pid=259) INFO 03-24 02:47:12 [gpu_worker.py:456] Available KV cache memory: 59.55 GiB\n",
      "(EngineCore pid=259) INFO 03-24 02:47:12 [kv_cache_utils.py:1316] GPU KV cache size: 1,115,056 tokens\n",
      "(EngineCore pid=259) INFO 03-24 02:47:12 [kv_cache_utils.py:1321] Maximum concurrency for 4,096 tokens per request: 272.23x\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "(EngineCore pid=259) 2026-03-24 02:47:12,680 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process starts ...\n",
      "(EngineCore pid=259) 2026-03-24 02:47:12,692 - INFO - autotuner.py:268 - flashinfer.jit: [Autotuner]: Autotuning process ends\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(EngineCore pid=259) INFO 03-24 02:47:13 [core.py:281] init engine (profile, create kv cache, warmup model) took 9.10 seconds\n",
      "(EngineCore pid=259) INFO 03-24 02:47:13 [vllm.py:754] Asynchronous scheduling is enabled.\n",
      "(EngineCore pid=259) WARNING 03-24 02:47:13 [vllm.py:788] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none\n",
      "(EngineCore pid=259) WARNING 03-24 02:47:13 [vllm.py:799] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.\n",
      "(EngineCore pid=259) INFO 03-24 02:47:13 [vllm.py:964] Cudagraph is disabled under eager mode\n",
      "(EngineCore pid=259) INFO 03-24 02:47:13 [compilation.py:289] Enabled custom fusions: norm_quant, act_quant\n",
      "INFO 03-24 02:47:13 [llm.py:391] Supported tasks: ['generate']\n",
      "Khởi chạy máy chủ suy luận của Kaggle...\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "import time\n",
    "import math\n",
    "import re           \n",
    "import glob         \n",
    "import traceback\n",
    "import contextlib\n",
    "import multiprocessing\n",
    "import tarfile\n",
    "import subprocess\n",
    "import site         \n",
    "from collections import Counter\n",
    "from io import StringIO\n",
    "import torch\n",
    "import polars as pl\n",
    "\n",
    "# ==========================================\n",
    "# FIX LỖI KAGGLE T4 GPU (UNIVERSAL BYPASS)\n",
    "# ==========================================\n",
    "WRITABLE_DIR = \"/kaggle/working/cuda_lib\"\n",
    "os.makedirs(WRITABLE_DIR, exist_ok=True)\n",
    "symlink_path = os.path.join(WRITABLE_DIR, \"libcuda.so.1\")\n",
    "target_path = \"/usr/local/cuda/lib64/stubs/libcuda.so\"\n",
    "if not os.path.exists(symlink_path) and os.path.exists(target_path):\n",
    "    try:\n",
    "        os.symlink(target_path, symlink_path)\n",
    "    except Exception:\n",
    "        pass\n",
    "os.environ[\"LD_LIBRARY_PATH\"] = f\"{WRITABLE_DIR}:/usr/local/cuda/lib64/stubs:\" + os.environ.get(\"LD_LIBRARY_PATH\", \"\")\n",
    "\n",
    "# ==========================================\n",
    "# CÀI ĐẶT VLLM OFFLINE (BẰNG PYTHON THUẦN TÚY)\n",
    "# ==========================================\n",
    "TAR_PATH = \"/kaggle/input/notebooks/saketposwal/aimo-3-vllm-v18/wheels.tar.gz\"\n",
    "EXTRACT_DIR = \"/kaggle/working/vllm_wheels\"\n",
    "os.makedirs(EXTRACT_DIR, exist_ok=True)\n",
    "\n",
    "if os.path.exists(TAR_PATH):\n",
    "    print(f\"Đang giải nén {TAR_PATH}...\")\n",
    "    with tarfile.open(TAR_PATH, \"r:gz\") as tar:\n",
    "        tar.extractall(path=EXTRACT_DIR)\n",
    "else:\n",
    "    print(f\"LỖI: Không tìm thấy file {TAR_PATH}\")\n",
    "\n",
    "wheels_to_delete = [\"protobuf-*.whl\", \"pillow-*.whl\", \"Pillow-*.whl\"]\n",
    "for pattern in wheels_to_delete:\n",
    "    for wheel_path in glob.glob(os.path.join(EXTRACT_DIR, \"**\", pattern), recursive=True):\n",
    "        print(f\"Đang xóa wheel để bảo vệ hệ thống: {wheel_path}\")\n",
    "        try:\n",
    "            os.remove(wheel_path)\n",
    "        except Exception as e:\n",
    "            pass\n",
    "\n",
    "print(\"Đang patch metadata protobuf để vượt qua dependency check của pip...\")\n",
    "site_packages = site.getsitepackages() + [site.getusersitepackages()]\n",
    "for sp in site_packages:\n",
    "    for dist_info in glob.glob(os.path.join(sp, \"protobuf-*.dist-info\")):\n",
    "        metadata_path = os.path.join(dist_info, \"METADATA\")\n",
    "        if os.path.exists(metadata_path):\n",
    "            try:\n",
    "                with open(metadata_path, \"r\") as f:\n",
    "                    content = f.read()\n",
    "                content = re.sub(r\"^Version:\\s*.*$\", \"Version: 5.29.6\", content, flags=re.MULTILINE)\n",
    "                with open(metadata_path, \"w\") as f:\n",
    "                    f.write(content)\n",
    "                new_dist_info = re.sub(r\"protobuf-[\\d\\.]+\\.dist-info\", \"protobuf-5.29.6.dist-info\", dist_info)\n",
    "                if dist_info != new_dist_info:\n",
    "                    os.rename(dist_info, new_dist_info)\n",
    "            except Exception as e:\n",
    "                pass\n",
    "\n",
    "target_wheels_dir = EXTRACT_DIR\n",
    "for root, dirs, files in os.walk(EXTRACT_DIR):\n",
    "    if any(f.endswith('.whl') for f in files):\n",
    "        target_wheels_dir = root\n",
    "        break\n",
    "\n",
    "print(f\"Đang cài đặt vLLM từ: {target_wheels_dir}\")\n",
    "subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"--no-index\", f\"--find-links={target_wheels_dir}\", \"vllm\"])\n",
    "\n",
    "# ==========================================\n",
    "# IMPORT CÁC THƯ VIỆN SAU KHI CÀI ĐẶT\n",
    "# ==========================================\n",
    "from vllm import LLM, SamplingParams\n",
    "sys.path.append('/kaggle/input/competitions/ai-mathematical-olympiad-progress-prize-3/kaggle_evaluation')\n",
    "import aimo_3_inference_server\n",
    "\n",
    "# ==========================================\n",
    "# 1. PYTHON REPL (MÔI TRƯỜNG THỰC THI CODE)\n",
    "# ==========================================\n",
    "class PythonREPL:\n",
    "    def __init__(self, timeout=15): # Giảm timeout xuống 15s để tránh kẹt hệ thống\n",
    "        self.timeout = timeout\n",
    "\n",
    "    def _execute_in_process(self, code: str, return_dict: dict):\n",
    "        output_buffer = StringIO()\n",
    "        with contextlib.redirect_stdout(output_buffer):\n",
    "            try:\n",
    "                exec_globals = {'math': math, 'sympy': __import__('sympy')}\n",
    "                exec(code, exec_globals)\n",
    "                return_dict['output'] = output_buffer.getvalue()\n",
    "                return_dict['error'] = None\n",
    "            except Exception as e:\n",
    "                return_dict['output'] = output_buffer.getvalue()\n",
    "                return_dict['error'] = traceback.format_exc()\n",
    "\n",
    "    def execute(self, code: str) -> str:\n",
    "        # SỬA LỖI TRÀN BỘ NHỚ: Sử dụng 'with' để dọn dẹp Manager\n",
    "        with multiprocessing.Manager() as manager:\n",
    "            return_dict = manager.dict()\n",
    "            p = multiprocessing.Process(target=self._execute_in_process, args=(code, return_dict))\n",
    "            p.start()\n",
    "            p.join(self.timeout)\n",
    "\n",
    "            if p.is_alive():\n",
    "                p.terminate()\n",
    "                p.join()\n",
    "                return \"Timeout Error: Execution exceeded 15 seconds.\"\n",
    "            \n",
    "            output = return_dict.get('output', '')\n",
    "            error = return_dict.get('error', None)\n",
    "            \n",
    "            if error:\n",
    "                return f\"Execution Output:\\n{output}\\nError:\\n{error}\"\n",
    "            elif not output.strip():\n",
    "                return \"Code executed successfully but printed no output. Please use print() to output the result.\"\n",
    "            else:\n",
    "                return f\"Execution Output:\\n{output}\"\n",
    "\n",
    "# ==========================================\n",
    "# 2. TOÁN TỬ VÀ AGENT TƯ DUY\n",
    "# ==========================================\n",
    "SYSTEM_PROMPT = \"\"\"You are an expert mathematical reasoning agent. To solve the math problem, you must write a Python script using the `sympy` or `math` libraries.\n",
    "1. Think step-by-step.\n",
    "2. Write Python code inside ```python ... ``` blocks to calculate intermediate or final results.\n",
    "3. ALWAYS print the final result using `print()`. \n",
    "4. Analyze the output of your code.\n",
    "5. The final answer must be a single non-negative integer. \n",
    "6. When you are certain of the final integer answer, output it in the format: \\\\boxed{answer}.\"\"\"\n",
    "\n",
    "def extract_code(text: str) -> str:\n",
    "    pattern = r'```python(.*?)```'\n",
    "    matches = re.findall(pattern, text, re.DOTALL)\n",
    "    return matches[-1].strip() if matches else \"\"\n",
    "\n",
    "def extract_boxed_answer(text: str) -> str:\n",
    "    pattern = r'\\\\boxed\\{([^{}]*)\\}'\n",
    "    matches = re.findall(pattern, text)\n",
    "    if matches:\n",
    "        num_matches = re.findall(r'\\d+', matches[-1])\n",
    "        if num_matches:\n",
    "            return num_matches[-1]\n",
    "    return \"\"\n",
    "\n",
    "def solve_problem_agentic(problem: str, llm: LLM, sampling_params: SamplingParams, max_iterations=3):\n",
    "    # GIẢM MAX_ITERATIONS xuống 3 để tránh TimeOut trong lúc submit\n",
    "    repl = PythonREPL(timeout=15)\n",
    "    tokenizer = llm.get_tokenizer()\n",
    "    \n",
    "    messages = [\n",
    "        {\"role\": \"system\", \"content\": SYSTEM_PROMPT},\n",
    "        {\"role\": \"user\", \"content\": problem}\n",
    "    ]\n",
    "    \n",
    "    for i in range(max_iterations):\n",
    "        prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
    "        outputs = llm.generate([prompt], sampling_params, use_tqdm=False)\n",
    "        response_text = outputs[0].outputs[0].text\n",
    "        \n",
    "        messages.append({\"role\": \"assistant\", \"content\": response_text})\n",
    "        \n",
    "        final_answer = extract_boxed_answer(response_text)\n",
    "        if final_answer:\n",
    "            return final_answer\n",
    "            \n",
    "        code = extract_code(response_text)\n",
    "        if code:\n",
    "            observation = repl.execute(code)\n",
    "            messages.append({\n",
    "                \"role\": \"user\", \n",
    "                \"content\": f\"Observation from Python execution:\\n```output\\n{observation}\\n```\\nPlease continue.\"\n",
    "            })\n",
    "        else:\n",
    "            messages.append({\n",
    "                \"role\": \"user\", \n",
    "                \"content\": \"You didn't write any Python code. Please provide the final answer in \\\\boxed{}.\"\n",
    "            })\n",
    "            \n",
    "    fallback_prompt = \"You have run out of iterations. Provide your best guess for the final non-negative integer answer directly in \\\\boxed{} format.\"\n",
    "    messages.append({\"role\": \"user\", \"content\": fallback_prompt})\n",
    "    \n",
    "    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
    "    outputs = llm.generate([prompt], sampling_params, use_tqdm=False)\n",
    "    final_response = outputs[0].outputs[0].text\n",
    "    \n",
    "    final_answer = extract_boxed_answer(final_response)\n",
    "    return final_answer if final_answer else \"0\"\n",
    "\n",
    "# ==========================================\n",
    "# 3. SELF-CONSISTENCY & MAJORITY VOTING\n",
    "# ==========================================\n",
    "def solve_with_majority_voting(problem: str, llm: LLM, num_samples=5) -> int:\n",
    "    # GIẢM SỐ LƯỢNG MẪU (num_samples) xuống 5 hoặc 7. \n",
    "    # 15 mẫu agentic (mỗi mẫu chạy tối đa 3 vòng) mất quá nhiều thời gian và gây rớt Submit.\n",
    "    print(f\"--- Solving Problem with {num_samples} Self-Consistency paths ---\")\n",
    "    sampling_params = SamplingParams(\n",
    "        temperature=0.7, \n",
    "        top_p=0.9, \n",
    "        max_tokens=1500, # Giảm max_tokens để an toàn hơn\n",
    "        stop=['```output']\n",
    "    )\n",
    "    \n",
    "    answers = []\n",
    "    for i in range(num_samples):\n",
    "        try:\n",
    "            ans_str = solve_problem_agentic(problem, llm, sampling_params, max_iterations=3)\n",
    "            ans_int = int(ans_str) % 1000  # Đảm bảo rule format của AIMO (nếu cần modulo, tùy đề, ở đây đảm bảo trả về int)\n",
    "            if ans_int >= 0:\n",
    "                answers.append(ans_int)\n",
    "        except Exception as e:\n",
    "            print(f\"Path {i} failed: {e}\")\n",
    "            pass\n",
    "            \n",
    "    if not answers:\n",
    "        return 0\n",
    "        \n",
    "    vote_counts = Counter(answers)\n",
    "    best_answer, count = vote_counts.most_common(1)[0]\n",
    "    print(f\"Selected Answer: {best_answer} (with {count} votes)\")\n",
    "    \n",
    "    return best_answer\n",
    "\n",
    "# ==========================================\n",
    "# 4. KHỞI TẠO MODEL TOÀN CỤC\n",
    "# ==========================================\n",
    "print(\"Initializing LLM Engine...\")\n",
    "num_gpus = torch.cuda.device_count()\n",
    "gpu_name = torch.cuda.get_device_name(0) if num_gpus > 0 else \"Unknown\"\n",
    "print(f\"Detected {num_gpus} GPUs. Type: {gpu_name}\")\n",
    "\n",
    "MODEL_PATH = \"/kaggle/input/models/adriansaezmartinez/qwen2.5-math-7b-instruct-awq/transformers/default/1\"\n",
    "try:\n",
    "    llm = LLM(\n",
    "        model=MODEL_PATH,\n",
    "        quantization=\"AWQ\",\n",
    "        tensor_parallel_size=max(1, num_gpus), \n",
    "        gpu_memory_utilization=0.85, \n",
    "        max_model_len=4096,\n",
    "        enforce_eager=True\n",
    "    )\n",
    "except Exception as e:\n",
    "    print(f\"Failed to load model: {e}\")\n",
    "    llm = None\n",
    "\n",
    "# ==========================================\n",
    "# 5. KAGGLE INFERENCE SERVER INTEGRATION\n",
    "# ==========================================\n",
    "def predict(test_df: pl.DataFrame, sample_prediction_df: pl.DataFrame) -> pl.DataFrame:\n",
    "    # Bảo vệ an toàn tuyệt đối cho API vòng lập\n",
    "    predictions = []\n",
    "    \n",
    "    for i in range(len(test_df)):\n",
    "        problem_id = test_df[\"id\"][i]\n",
    "        problem_text = test_df[\"problem\"][i]\n",
    "        print(f\"\\n{'='*50}\\nProcessing Problem ID: {problem_id}\\n{'='*50}\")\n",
    "        \n",
    "        try:\n",
    "            if llm is None:\n",
    "                final_answer = 0\n",
    "            else:\n",
    "                # Điều chỉnh số lượt voting sao cho tối ưu, tôi kiến nghị dùng 5 cho an toàn\n",
    "                final_answer = solve_with_majority_voting(problem_text, llm, num_samples=5)\n",
    "        except Exception as e:\n",
    "            print(f\"Critical error on problem {problem_id}: {e}\")\n",
    "            final_answer = 0  # Trả về 0 nếu code sập để không bị tạch toàn bộ file submit\n",
    "            \n",
    "        predictions.append(final_answer)\n",
    "\n",
    "        # Dọn dẹp GPU cache sau mỗi bài toán để tránh OOM\n",
    "        if torch.cuda.is_available():\n",
    "            torch.cuda.empty_cache()\n",
    "            \n",
    "    # Đảm bảo kiểu dữ liệu trả về đúng định dạng Int64 của hệ thống Kaggle\n",
    "    submission = sample_prediction_df.with_columns(pl.Series(\"answer\", predictions, dtype=pl.Int64))\n",
    "    return submission\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # ĐÃ XÓA KHỐI CODE TẠO FILE DUMMY PARQUET DO GÂY RA LỖI OVERWRITE TRONG QUÁ TRÌNH SUBMIT\n",
    "    print(\"Khởi chạy máy chủ suy luận của Kaggle...\")\n",
    "    inference_server = aimo_3_inference_server.AIMO3InferenceServer(predict)\n",
    "    inference_server.serve()"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "nvidiaH100",
   "dataSources": [
    {
     "databundleVersionId": 14559231,
     "sourceId": 118448,
     "sourceType": "competition"
    },
    {
     "databundleVersionId": 9997483,
     "modelId": 150852,
     "modelInstanceId": 127932,
     "sourceId": 150653,
     "sourceType": "modelInstanceVersion"
    },
    {
     "sourceId": 305327396,
     "sourceType": "kernelVersion"
    }
   ],
   "isGpuEnabled": true,
   "isInternetEnabled": false,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 208.899301,
   "end_time": "2026-03-24T02:47:16.421867+00:00",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-03-24T02:43:47.522566+00:00",
   "version": "2.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
